# Generated by Django 5.2.17 on 2026-09-27 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCache',
            fields=[
                ('query', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteCache',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('meters', models.FloatField()),
                ('seconds', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manuell'), ('nuliga', 'nuLiga'), ('handballnet', 'handball.net'), ('handball360', 'Handball360'), ('file', 'Datei')], default='manual', max_length=20, verbose_name='Quelle')),
                ('source_uid', models.CharField(blank=True, max_length=200, null=True)),
                ('sequence', models.IntegerField(default=0)),
                ('last_modified', models.CharField(blank=True, max_length=40, null=True)),
                ('spielnummer', models.CharField(blank=True, help_text='z. B. 2627SAROLCJMA0501', max_length=40, verbose_name='Spiel-Nr.')),
                ('game_datetime', models.DateTimeField(verbose_name='Datum & Uhrzeit')),
                ('home_team', models.CharField(max_length=160, verbose_name='Heim')),
                ('away_team', models.CharField(blank=True, max_length=160, verbose_name='Gast')),
                ('league', models.CharField(max_length=200, verbose_name='Liga (Anzeige)')),
                ('league_key', models.CharField(blank=True, max_length=60, null=True, verbose_name='Spielklasse (Regelwerk)')),
                ('competition_type', models.CharField(choices=[('championship', 'Meisterschaft'), ('cup', 'Pokal'), ('friendly', 'Freundschaftsspiel'), ('tournament', 'Turnier')], default='championship', max_length=20, verbose_name='Wettbewerb')),
                ('cup_round', models.CharField(blank=True, max_length=30, null=True, verbose_name='Pokalrunde')),
                ('tournament_group', models.CharField(blank=True, max_length=40, null=True, verbose_name='Turnier-Art')),
                ('tournament_tier', models.CharField(blank=True, max_length=40, null=True, verbose_name='Staffel (Spielzeit)')),
                ('games_count', models.PositiveIntegerField(default=1, verbose_name='Anzahl Spiele')),
                ('hall', models.CharField(blank=True, max_length=200, verbose_name='Halle')),
                ('hall_address', models.CharField(blank=True, max_length=300, verbose_name='Hallenadresse')),
                ('role', models.CharField(choices=[('sr1', 'Schiedsrichter 1'), ('sr2', 'Schiedsrichter 2'), ('esr', 'Einzelschiedsrichter'), ('zns', 'Zeitnehmer/Sekretär')], default='sr1', max_length=3, verbose_name='Rolle')),
                ('status', models.CharField(choices=[('angesetzt', 'Angesetzt'), ('bestätigt', 'Bestätigt'), ('verlegt', 'Verlegt'), ('abgesagt', 'Abgesagt'), ('ausgefallen_angereist', 'Ausgefallen (angereist)'), ('ausgefallen_nicht_angereist', 'Ausgefallen (nicht angereist)'), ('geleitet', 'Geleitet')], default='angesetzt', max_length=30)),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('travel_km', models.FloatField(blank=True, null=True, verbose_name='Fahrt-km (Hin + Rück)')),
                ('travel_km_manual', models.BooleanField(default=False, verbose_name='km-Wert manuell (nicht aufteilen)')),
                ('travel_km_auto', models.BooleanField(default=False, help_text='km wurden automatisch berechnet')),
                ('travel_minutes', models.FloatField(blank=True, help_text='Fahrzeit einfach (Minuten)', null=True)),
                ('travel_mitfahrer', models.BooleanField(default=False, verbose_name='Mitfahrt im Gespann (0,32 €/km)')),
                ('pnv_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='PNV-Einzelfahrtkosten (€)')),
                ('other_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Sonstige Auslagen (€)')),
                ('expense_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('expense_breakdown', models.JSONField(blank=True, default=list)),
                ('expense_warnings', models.JSONField(blank=True, default=list)),
                ('rulepack_version', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einsaetze', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Einsatz',
                'verbose_name_plural': 'Einsätze',
                'ordering': ['-game_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=9)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pdf', models.FileField(blank=True, upload_to='quittungen/')),
                ('payout_status', models.CharField(choices=[('offen', 'offen'), ('erhalten', 'erhalten'), ('nicht_ausgezahlt', 'nicht ausgezahlt')], default='offen', max_length=20, verbose_name='Auszahlung')),
                ('payout_date', models.DateField(blank=True, null=True, verbose_name='ausgezahlt am')),
                ('payer', models.CharField(blank=True, max_length=120, verbose_name='ausgezahlt von')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignments', models.ManyToManyField(related_name='quittungen', to='schiedsrichter.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quittungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quittung',
                'verbose_name_plural': 'Quittungen',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['user', 'game_datetime'], name='schiedsrich_user_id_798514_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('user', 'source', 'source_uid'), name='uniq_einsatz_quelle'),
        ),
    ]
