# Generated by Django 5.2.17 on 2026-09-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schiedsrichter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='km_fehler',
            field=models.CharField(blank=True, help_text='Letzter Fehler der automatischen km-Berechnung', max_length=200),
        ),
    ]
