# Generated by Django 5.2.17 on 2026-09-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schiedsrichter', '0002_km_fehler'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='automatisch',
            field=models.BooleanField(default=False, help_text='3 Tage vor dem Spiel automatisch erstellt'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='pdf_stand',
            field=models.CharField(blank=True, help_text='Fingerabdruck der Daten, aus denen das PDF erzeugt wurde', max_length=64),
        ),
    ]
