# Generated by Django 5.2.17 on 2026-09-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schiedsrichter', '0003_quittung_automatisch'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='hallennummer',
            field=models.CharField(blank=True, help_text='nuLiga-/Handball360-Hallennummer, z. B. 210048 – steht auf dem Abrechnungsbogen', max_length=20, verbose_name='Hallen-Nr.'),
        ),
    ]
