# Generated by Django 5.2.17 on 2026-09-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schiedsrichter', '0005_quittung_je_spiel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Halle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('adresse_key', models.CharField(blank=True, db_index=True, max_length=300)),
                ('nummer', models.CharField(blank=True, max_length=20, verbose_name='Hallen-Nr.')),
                ('nummer_stand', models.DateTimeField(blank=True, null=True, verbose_name='Nummer zuletzt gesehen am (Spiel)')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Halle',
                'verbose_name_plural': 'Hallen',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='assignment',
            name='hallennummer',
            field=models.CharField(blank=True, help_text='Wird automatisch aus früheren Spielen in dieser Halle übernommen. Ist sie gesetzt, steht sie statt des Hallennamens auf dem Bogen.', max_length=20, verbose_name='Hallen-Nr. (optional)'),
        ),
    ]
