# Generated by Django 5.2.17 on 2026-09-27 18:56

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('verbaende', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('saison', models.CharField(default='2026/27', max_length=9)),
                ('verein', models.CharField(blank=True, max_length=120)),
                ('ist_schiedsrichter', models.BooleanField(default=False, verbose_name='Schiedsrichter/in')),
                ('ist_spieler', models.BooleanField(default=False, verbose_name='Spieler/in')),
                ('ist_trainer', models.BooleanField(default=False, verbose_name='Trainer/in')),
                ('ist_funktionaer', models.BooleanField(default=False, verbose_name='Vereins-/Verbandsfunktionär/in')),
                ('strasse', models.CharField(blank=True, max_length=120, verbose_name='Straße')),
                ('plz', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('ort', models.CharField(blank=True, max_length=80)),
                ('telefon', models.CharField(blank=True, max_length=40)),
                ('iban', models.CharField(blank=True, max_length=40, verbose_name='IBAN')),
                ('standard_rolle', models.CharField(choices=[('sr1', 'Schiedsrichter 1'), ('sr2', 'Schiedsrichter 2'), ('esr', 'Einzelschiedsrichter'), ('zns', 'Zeitnehmer/Sekretär')], default='sr1', max_length=3, verbose_name='Standard-SR-Rolle')),
                ('partner_name', models.CharField(blank=True, max_length=120, verbose_name='Gespannpartner/in (Name, Vorname)')),
                ('partner_adresse', models.CharField(blank=True, max_length=200, verbose_name='Adresse Gespannpartner/in')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('verband', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mitglieder', to='verbaende.verband')),
            ],
            options={
                'verbose_name': 'Benutzer',
                'verbose_name_plural': 'Benutzer',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
