# Generated by Django 5.2.17 on 2026-09-27 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.CharField(max_length=20, unique=True, verbose_name='Kürzel')),
                ('name', models.CharField(max_length=120)),
                ('sportart', models.CharField(choices=[('handball', 'Handball')], default='handball', max_length=20)),
                ('aktiv', models.BooleanField(default=True, verbose_name='zur Auswahl anbieten')),
                ('reihenfolge', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Verband',
                'verbose_name_plural': 'Verbände',
                'ordering': ['reihenfolge', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RulePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.CharField(max_length=9)),
                ('version', models.CharField(max_length=40)),
                ('daten', models.JSONField()),
                ('aktiv', models.BooleanField(default=True)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('verband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regelwerke', to='verbaende.verband')),
            ],
            options={
                'verbose_name': 'Regelwerk',
                'verbose_name_plural': 'Regelwerke',
                'unique_together': {('verband', 'saison', 'version')},
            },
        ),
    ]
